language: java
jdk:
 - oraclejdk8
deploy:
  provider: heroku
  app: car-cost-tracker
  api_key:
    secure: R7zoyxZknqTtOKssnOtsHC6nB+H8/m1zljbwxek4r8IqpCjdkItVjHRxYyOCx7ioNIvZuJh+uvQQuIY/XWq6sndzapwK2DTK/dVLYOYm0hPc1oHC6H3Rs0DtWnn9vhU03Z7PtRUYEECr2Gz2SwOMP3Ms5QiWxfIpJ7pbN9q0A2krIFqXHYnxoPRGsnKDEhftys4TQM8vuvns0JAiJgXHQC4pPPH/0Uf1AR5SctQqnCmf8CjsIIWhnFGum4S8wC+ruYtCerd8QpxctKTf8jvy/IDNXRkLndwV8TI4gGpHDHkFCjQROSUP6Azx6S/zEX/sGBi3raJqcCB7UZlSSnkZ8Psi98d0AUzAgejX87/paqxFX2/SGqvnsTAfs7H0nD2OqhvfkNKO1EgKFlGXukXBrzAR4/UeCaqx3T+PoGJ//Y78nA8UMFzOT5ZHwBQghVzHoKcYRYo0OW7kM+jqdI8aInrOEr3VwqoY/nS8ujeSYq6ZAgU2Mlx3GgSEBdLrkXrn1eWLIEPVhO7qOV+SPz2levHV3jnJRdNGFVImkaRs/VVa2aHDen5h3S+AqAYUGb4yG0qfCLMU8sROQXneFQW8kjN0ZXenEdc5f01IB7pPb1/eBTxw8pwVmbdE5gTcLLW1Yq6+2I6Shk/YP0YPXLyaPC6yl+3snr8uqPHly0r2dKA=
