INSERT INTO make(id, name, logo_url) VALUES ('acura', 'ACURA', 'https://s1.cdn.autoevolution.com/images/producers/acura-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('alfa-romeo', 'ALFA ROMEO', 'https://s1.cdn.autoevolution.com/images/producers/alfa-romeo-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('ariel', 'ARIEL', 'https://s1.cdn.autoevolution.com/images/producers/ariel-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('aro', 'ARO', 'https://s1.cdn.autoevolution.com/images/producers/aro-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('aston-martin', 'ASTON MARTIN', 'https://s1.cdn.autoevolution.com/images/producers/aston-martin-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('audi', 'AUDI', 'https://s1.cdn.autoevolution.com/images/producers/audi-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('bentley', 'BENTLEY', 'https://s1.cdn.autoevolution.com/images/producers/bentley-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('bmw', 'BMW', 'https://s1.cdn.autoevolution.com/images/producers/bmw-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('bristol', 'BRISTOL', 'https://s1.cdn.autoevolution.com/images/producers/bristol-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('bufori', 'BUFORI', 'https://s1.cdn.autoevolution.com/images/producers/bufori-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('bugatti', 'BUGATTI', 'https://s1.cdn.autoevolution.com/images/producers/bugatti-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('buick', 'BUICK', 'https://s1.cdn.autoevolution.com/images/producers/buick-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('cadillac', 'CADILLAC', 'https://s1.cdn.autoevolution.com/images/producers/cadillac-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('caterham', 'CATERHAM', 'https://s1.cdn.autoevolution.com/images/producers/caterham-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('chevrolet', 'CHEVROLET', 'https://s1.cdn.autoevolution.com/images/producers/chevrolet-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('chrysler', 'CHRYSLER', 'https://s1.cdn.autoevolution.com/images/producers/chrysler-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('citroen', 'CITROEN', 'https://s1.cdn.autoevolution.com/images/producers/citroen-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('dacia', 'DACIA', 'https://s1.cdn.autoevolution.com/images/producers/dacia-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('daewoo', 'DAEWOO', 'https://s1.cdn.autoevolution.com/images/producers/daewoo-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('daihatsu', 'DAIHATSU', 'https://s1.cdn.autoevolution.com/images/producers/daihatsu-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('datsun', 'DATSUN', 'https://s1.cdn.autoevolution.com/images/producers/datsun-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('dmc', 'DMC', 'https://s1.cdn.autoevolution.com/images/producers/dmc-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('dodge', 'DODGE', 'https://s1.cdn.autoevolution.com/images/producers/dodge-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('donkervoort', 'DONKERVOORT', 'https://s1.cdn.autoevolution.com/images/producers/donkervoort-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('dr-motor', 'DR MOTOR', 'https://s1.cdn.autoevolution.com/images/producers/dr-motor-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('ferrari', 'FERRARI', 'https://s1.cdn.autoevolution.com/images/producers/ferrari-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('fiat', 'FIAT', 'https://s1.cdn.autoevolution.com/images/producers/fiat-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('fisker', 'FISKER', 'https://s1.cdn.autoevolution.com/images/producers/fisker-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('ford', 'FORD', 'https://s1.cdn.autoevolution.com/images/producers/ford-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('fso', 'FSO', 'https://s1.cdn.autoevolution.com/images/producers/fso-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('geely', 'GEELY', 'https://s1.cdn.autoevolution.com/images/producers/geely-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('genesis', 'GENESIS', 'https://s1.cdn.autoevolution.com/images/producers/genesis-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('gmc', 'GMC', 'https://s1.cdn.autoevolution.com/images/producers/gmc-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('gta-motor', 'GTA Motor', 'https://s1.cdn.autoevolution.com/images/producers/gta-motor-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('hindustan', 'HINDUSTAN', 'https://s1.cdn.autoevolution.com/images/producers/hindustan-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('holden', 'HOLDEN', 'https://s1.cdn.autoevolution.com/images/producers/holden-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('honda', 'HONDA', 'https://s1.cdn.autoevolution.com/images/producers/honda-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('hummer', 'HUMMER', 'https://s1.cdn.autoevolution.com/images/producers/hummer-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('hyundai', 'HYUNDAI', 'https://s1.cdn.autoevolution.com/images/producers/hyundai-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('infiniti', 'INFINITI', 'https://s1.cdn.autoevolution.com/images/producers/infiniti-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('isuzu', 'ISUZU', 'https://s1.cdn.autoevolution.com/images/producers/isuzu-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('jaguar', 'JAGUAR', 'https://s1.cdn.autoevolution.com/images/producers/jaguar-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('jeep', 'JEEP', 'https://s1.cdn.autoevolution.com/images/producers/jeep-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('kia', 'KIA', 'https://s1.cdn.autoevolution.com/images/producers/kia-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('koenigsegg', 'KOENIGSEGG', 'https://s1.cdn.autoevolution.com/images/producers/koenigsegg-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('ktm', 'KTM', 'https://s1.cdn.autoevolution.com/images/producers/ktm-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('lada', 'LADA', 'https://s1.cdn.autoevolution.com/images/producers/lada-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('lamborghini', 'LAMBORGHINI', 'https://s1.cdn.autoevolution.com/images/producers/lamborghini-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('lancia', 'LANCIA', 'https://s1.cdn.autoevolution.com/images/producers/lancia-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('land-rover', 'LAND ROVER', 'https://s1.cdn.autoevolution.com/images/producers/land-rover-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('lexus', 'LEXUS', 'https://s1.cdn.autoevolution.com/images/producers/lexus-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('lincoln', 'LINCOLN', 'https://s1.cdn.autoevolution.com/images/producers/lincoln-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('lotus', 'LOTUS', 'https://s1.cdn.autoevolution.com/images/producers/lotus-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('mahindra', 'Mahindra', 'https://s1.cdn.autoevolution.com/images/producers/mahindra-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('marussia', 'MARUSSIA', 'https://s1.cdn.autoevolution.com/images/producers/marussia-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('maruti-suzuki', 'MARUTI SUZUKI', 'https://s1.cdn.autoevolution.com/images/producers/maruti-suzuki-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('maserati', 'MASERATI', 'https://s1.cdn.autoevolution.com/images/producers/maserati-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('maybach', 'MAYBACH', 'https://s1.cdn.autoevolution.com/images/producers/maybach-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('mazda', 'MAZDA', 'https://s1.cdn.autoevolution.com/images/producers/mazda-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('mclaren', 'MCLAREN', 'https://s1.cdn.autoevolution.com/images/producers/mclaren-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('mercedes-benz', 'MERCEDES BENZ', 'https://s1.cdn.autoevolution.com/images/producers/mercedes-benz-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('mercury', 'MERCURY', 'https://s1.cdn.autoevolution.com/images/producers/mercury-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('mg', 'MG', 'https://s1.cdn.autoevolution.com/images/producers/mg-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('mini', 'MINI', 'https://s1.cdn.autoevolution.com/images/producers/mini-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('mitsubishi', 'MITSUBISHI', 'https://s1.cdn.autoevolution.com/images/producers/mitsubishi-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('morgan', 'MORGAN', 'https://s1.cdn.autoevolution.com/images/producers/morgan-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('nissan', 'NISSAN', 'https://s1.cdn.autoevolution.com/images/producers/nissan-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('oldsmobile', 'OLDSMOBILE', 'https://s1.cdn.autoevolution.com/images/producers/oldsmobile-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('opel', 'OPEL', 'https://s1.cdn.autoevolution.com/images/producers/opel-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('pagani', 'PAGANI', 'https://s1.cdn.autoevolution.com/images/producers/pagani-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('panoz', 'PANOZ', 'https://s1.cdn.autoevolution.com/images/producers/panoz-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('perodua', 'PERODUA', 'https://s1.cdn.autoevolution.com/images/producers/perodua-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('peugeot', 'PEUGEOT', 'https://s1.cdn.autoevolution.com/images/producers/peugeot-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('pontiac', 'PONTIAC', 'https://s1.cdn.autoevolution.com/images/producers/pontiac-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('porsche', 'PORSCHE', 'https://s1.cdn.autoevolution.com/images/producers/porsche-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('proton', 'PROTON', 'https://s1.cdn.autoevolution.com/images/producers/proton-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('qoros', 'QOROS', 'https://s1.cdn.autoevolution.com/images/producers/qoros-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('ram-trucks', 'RAM Trucks', 'https://s1.cdn.autoevolution.com/images/producers/ram-trucks-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('renault', 'RENAULT', 'https://s1.cdn.autoevolution.com/images/producers/renault-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('rolls-royce', 'ROLLS-ROYCE', 'https://s1.cdn.autoevolution.com/images/producers/rolls-royce-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('saab', 'SAAB', 'https://s1.cdn.autoevolution.com/images/producers/saab-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('saleen', 'SALEEN', 'https://s1.cdn.autoevolution.com/images/producers/saleen-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('samsung', 'SAMSUNG', 'https://s1.cdn.autoevolution.com/images/producers/samsung-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('santana', 'SANTANA', 'https://s1.cdn.autoevolution.com/images/producers/santana-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('saturn', 'SATURN', 'https://s1.cdn.autoevolution.com/images/producers/saturn-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('scion', 'SCION', 'https://s1.cdn.autoevolution.com/images/producers/scion-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('seat', 'SEAT', 'https://s1.cdn.autoevolution.com/images/producers/seat-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('skoda', 'SKODA', 'https://s1.cdn.autoevolution.com/images/producers/skoda-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('smart', 'SMART', 'https://s1.cdn.autoevolution.com/images/producers/smart-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('spyker', 'SPYKER', 'https://s1.cdn.autoevolution.com/images/producers/spyker-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('ssangyong', 'SSANGYONG', 'https://s1.cdn.autoevolution.com/images/producers/ssangyong-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('subaru', 'SUBARU', 'https://s1.cdn.autoevolution.com/images/producers/subaru-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('suzuki', 'SUZUKI', 'https://s1.cdn.autoevolution.com/images/producers/suzuki-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('tata-motors', 'TATA MOTORS', 'https://s1.cdn.autoevolution.com/images/producers/tata-motors-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('tesla-motors', 'TESLA MOTORS', 'https://s1.cdn.autoevolution.com/images/producers/tesla-motors-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('toyota', 'TOYOTA', 'https://s1.cdn.autoevolution.com/images/producers/toyota-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('tvr', 'TVR', 'https://s1.cdn.autoevolution.com/images/producers/tvr-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('vauxhall', 'VAUXHALL', 'https://s1.cdn.autoevolution.com/images/producers/vauxhall-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('volkswagen', 'VOLKSWAGEN', 'https://s1.cdn.autoevolution.com/images/producers/volkswagen-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('volvo', 'VOLVO', 'https://s1.cdn.autoevolution.com/images/producers/volvo-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('wiesmann', 'WIESMANN', 'https://s1.cdn.autoevolution.com/images/producers/wiesmann-sm.jpg');
INSERT INTO make(id, name, logo_url) VALUES ('zender', 'ZENDER', 'https://s1.cdn.autoevolution.com/images/producers/zender-sm.jpg');
